[build]
    functions = "netlify_functions"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[build.environment]
  REACT_APP_API_URL = "https://kaxc3oyqa2.execute-api.us-west-2.amazonaws.com/api/"

[[redirects]]
  from = "/api/*"
  to = "https://kaxc3oyqa2.execute-api.us-west-2.amazonaws.com/api/"
  status = 200
  force = true

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

